name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# permissions:
#   id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run lint
      - run: bun run build
      - uses: codecov/codecov-action@v4
      - name: nightly release
        if: |
          github.ref_name == 'main' &&
          !contains(github.event.head_commit.message, '[skip-release]') &&
          !startsWith(github.event.head_commit.message, 'docs')
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc &&
          bun run changelogen --canary nightly --publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: false
